services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.14.0
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      TZ: ${TZ:-Europe/Madrid}
    volumes:
      - nginx-proxy-manager-data:/data
      - nginx-proxy-manager-letsencrypt:/etc/letsencrypt

volumes:
  nginx-proxy-manager-data:
  nginx-proxy-manager-letsencrypt:
